---
sudo: false
cache:
  directories:
    - $HOME/.cpanm
    - $HOME/perl5
    - /var/tmp
    - $HOME/.nvm
addons:
  apt:
    packages:
    - build-essential
    - libgd2-xpm-dev
    - libssl-dev
    - git
    - libxml2-dev
    - libpango1.0-dev
    - imagemagick
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - cpanm  --quiet  --notest --skip-installed Dist::Zilla
  - dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm  --quiet   --notest  --skip-installed --mirror http://www.cpan.org/ --mirror http://duckpan.org/
  - dzil listdeps | grep -ve '^\W' | cpanm  --quiet   --notest  --skip-installed --mirror http://www.cpan.org/ --mirror http://duckpan.org/
  - find /home/travis/perl5 -name plackup
  - npm cache clean
  - npm install
language: perl
perl:
  - 5.16
node_js:
  - 4.2
script:
  - prove -lr -j1 t
  - grunt test-ia
env:
  global:
    secure: Vfwbe9/9Q/mACQVO6Dq6Jw1WM7CqAFEuqBfS+ukANy6uBgrnw32Sk7LGMYDHGwsaSmiCTz0cfvWZ2RcToCdTK4AyHAPPm/ry69Thnf+BtikE82voL9vv0kSlLZarBBZe7Ll2//sppjMGKdAYiEhYBPn2/3TOeIiYPKnFSsiIwLg=
