=head1 DuckDuckGo - Community Platform

B<New documentation in work! Please only try if you know what you do>

=head2 REQUIREMENTS

Requires perl 5.14.2< and:

  apt-get install build-essential libgd2-xpm-dev libssl-dev git wget libxml2-dev imagemagick

=head2 INSTALLATION

After checking out, you require to install the requirements. You must have
installed B<Dist::Zilla>, then you can do the following to install the base
Perl requirements:

  dzil authordeps --missing | cpanm
  dzil listdeps --missing | cpanm

Addtionally, you require to install DDGC deps from duckpan:

  duckpan DDGC::Static

When you checked out the repository you must once run this command to get a
base database installed in your home:

  script/ddgc_deploy_dev.pl

You might need to use the B<--kill> switch if you already have one, or want to
reset it:

  script/ddgc_deploy_dev.pl --kill

For the flags to work you need to generate the sprites used for the flags. This
process has to be repeated everytime the country flags are changing.

  script/ddgc_generate_flag_sprites.pl

=head2 DEVELOPING

You can start the web server, if you are inside the repository with:

  script/ddgc_web_server.pl -r -d

If you want todo any of the above activities with intense debug logging you can
use the following ENV variables before the command, like in this example:

  DBIC_TRACE_PROFILE=console DBIC_TRACE=1 script/ddgc_web_server.pl -r -d

The B<-r> switch assures that it reloads itself, if some of the codefiles are
changed. For changes on templates he will not restart. (If you work on the blog
you sadly have to restart by hand if you change the data file).

The B<-d> switch sets the web server into debugging mode. This activates a side
bar with additional request informations, and also shows you much more
informations on the terminal. If you don't want those, you can just deactivate
it. For work on HTML/CSS or the blog it might disturb.

=head3 ACCOUNTS

We prepared some accounts for testing in the default setup, those can all be
accessed with random passwords (yes, you can't test wrong password yet, sorry).

The following account exist:

* B<testone> An admin, who is native german, but also speaks english.

* B<testtwo> A normal user who speaks spanish, with public profile.

* B<testthree> A translation_manager who speaks english, arabic and german.

* B<testfour> An admin, who speaks german, spain and english.

* B<testfive> A normal user without public profile, who speaks russian and
   english.

* Additionally there exist B<test1> till B<test100> all without any setup.


