copy instant_answer (
	id,
	name,
	description,
	perl_module,
	dev_milestone,
	status,
	repo,
	src_name,
	unsafe,
	src_domain,
	developer,
	meta_id,
	is_stackexchange,
	public,
	maintainer,
	production_state
) from stdin;
academia_stackexchange	Academia Stack Exchange	Question and answer site for academics and those enrolled in higher education	DDG::Longtail::Academia	live	live	longtail	Academia Stack Exchange	0	academia.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	academia_stackexchange	1	1	{"github":"duckduckgo"}	offline
anime_stackexchange	Anime & MangaStack Exchange	Question and answer site for anime and manga fans	DDG::Longtail::Anime	live	live	longtail	Anime & Manga Stack Exchange	0	anime.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	anime_stackexchange	1	1	{"github":"duckduckgo"}	offline
arduino_stackexchange	Arduino Stack Exchange	Question and answer site for developers of open-source hardware and software that is compatible with Arduino	DDG::Longtail::Arduino	live	live	longtail	Arduino Stack Exchange	0	arduino.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	arduino_stackexchange	1	1	{"github":"duckduckgo"}	offline
astronomy_stackexchange	Astronomy Stack Exchange	Question and answer site for astronomers and astrophysicists	DDG::Longtail::Astronomy	live	live	longtail	Astronomy Stack Exchange	0	astronomy.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	astronomy_stackexchange	1	1	{"github":"duckduckgo"}	offline
aviation_stackexchange	Aviation Stack Exchange	Question and answer site for aircraft pilots, mechanics, and enthusiasts	DDG::Longtail::Aviation	live	live	longtail	Aviation Stack Exchange	0	aviation.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	aviation_stackexchange	1	1	{"github":"duckduckgo"}	offline
boardgames_stackexchange	Board & Card Games Stack Exchange	Question and answer site for people who like playing board games, designing board games or modifying the rules of existing board games	DDG::Longtail::BoardGames	live	live	longtail	Board & Card Games Stack Exchange	0	boardgames.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	boardgames_stackexchange	1	1	{"github":"duckduckgo"}	offline
bricks_stackexchange	Bricks Stack Exchange	Question and answer site for LEGO® and building block enthusiasts	DDG::Longtail::Bricks	live	live	longtail	Bricks Stack Exchange	0	bricks.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	bricks_stackexchange	1	1	{"github":"duckduckgo"}	offline
buddhism_stackexchange	Buddhism Stack Exchange	Question and answer site for people practicing or interested in Buddhist philosophy, teaching, and practice	DDG::Longtail::Buddhism	live	live	longtail	Buddhism Stack Exchange	0	buddhism.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	buddhism_stackexchange	1	1	{"github":"duckduckgo"}	offline
chemistry_stackexchange	Chemistry Stack Exchange	Question and answer site for scientists, academics, teachers and students	DDG::Longtail::Chemistry	live	live	longtail	Chemistry Stack Exchange	0	chemistry.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	chemistry_stackexchange	1	1	{"github":"duckduckgo"}	offline
civicrm_stackexchange	CiviCRM Stack Exchange	Question and answer site for administrators and users of the CiviCRM Constituent Relationship Management software	DDG::Longtail::CiviCRM	live	live	longtail	CiviCRM Stack Exchange	0	civicrm.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	civicrm_stackexchange	1	1	{"github":"duckduckgo"}	offline
codegolf_stackexchange	 Programming Puzzles & Code Golf Stack Exchange	Question and answer site for programming puzzle enthusiasts and code golfers	DDG::Longtail::CodeGolf	live	live	longtail	Programming Puzzles & Code Golf Stack Exchange	0	codegolf.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	codegolf_stackexchange	1	1	{"github":"duckduckgo"}	offline
codereview_stackexchange	Code Review Stack Exchange	Question and answer site for peer programmer code reviews	DDG::Longtail::CodeReview	live	live	longtail	Code Review Stack Exchange	0	codereview.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	codereview_stackexchange	1	1	{"github":"duckduckgo"}	offline
coffee_stackexchange	Coffee Stack Exchange	Question and answer site for people interested in all aspects of producing and consuming coffee	DDG::Longtail::Coffee	live	live	longtail	Coffee Stack Exchange	0	coffee.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	coffee_stackexchange	1	1	{"github":"duckduckgo"}	offline
cogsci_stackexchange	Cognitive Science Stack Exchange	Question and answer site for practitioners, researchers, and students in cognitive science, psychology, neuroscience, and psychiatry	DDG::Longtail::CognitiveScience	live	live	longtail	Cognitive Science Stack Exchange	0	cogsci.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	cogsci_stackexchange	1	1	{"github":"duckduckgo"}	offline
computergraphics_stackexchange	Computer Graphics Stack Exchange	Question and answer site for computer graphics researchers and programmers	DDG::Longtail::ComputerGraphics	live	live	longtail	Computer Graphics Stack Exchange	0	computergraphics.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	computergraphics_stackexchange	1	1	{"github":"duckduckgo"}	offline
craftcms_stackexchange	Craft CMS Stack Exchange	Question and answer site for administrators, end users, developers and designers for Craft CMS	DDG::Longtail::CraftCMS	live	live	longtail	Craft CMS Stack Exchange	0	craftcms.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	craftcms_stackexchange	1	1	{"github":"duckduckgo"}	offline
crypto_stackexchange	Cryptography Stack Exchange	Question and answer site for software developers, mathematicians and others interested in cryptography	DDG::Longtail::Cryptography	live	live	longtail	Cryptography Stack Exchange	0	crypto.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	crypto_stackexchange	1	1	{"github":"duckduckgo"}	offline
cs_stackexchange	Computer Science Stack Exchange	Question and answer site for students, researchers and practitioners of computer science	DDG::Longtail::ComputerScience	live	live	longtail	Computer Science Stack Exchange	0	cs.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	cs_stackexchange	1	1	{"github":"duckduckgo"}	offline
datascience_stackexchange	Data Science Stack Exchange	Question and answer site for Data science professionals, Machine Learning specialists, and those interested in learning more about the field	DDG::Longtail::Data Science	live	live	longtail	Data Science Stack Exchange	0	datascience.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	datascience_stackexchange	1	1	{"github":"duckduckgo"}	offline
dsp_stackexchange	Signal Processing Stack Exchange	Question and answer site for practitioners of the art and science of signal, image and video processing	DDG::Longtail::Signal Processing	live	live	longtail	Signal Processing Stack Exchange	0	dsp.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	dsp_stackexchange	1	1	{"github":"duckduckgo"}	offline
earthscience_stackexchange	Earth Science Stack Exchange	Question and answer site for those interested in the geology, meteorology, oceanography, and environmental sciences 	DDG::Longtail::EarthScience	live	live	longtail	Earth Science Stack Exchange	0	earthscience.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	earthscience_stackexchange	1	1	{"github":"duckduckgo"}	offline
ebooks_stackexchange	Ebooks Stack Exchange	Question and answer site for ebook publishers and readers	DDG::Longtail::Ebooks	live	live	longtail	Ebooks Stack Exchange	0	ebooks.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	ebooks_stackexchange	1	1	{"github":"duckduckgo"}	offline
economics_stackexchange	Economics Stack Exchange	Question and answer site for professional and academic economists and analysts	DDG::Longtail::Economics	live	live	longtail	Economics Stack Exchange	0	economics.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	economics_stackexchange	1	1	{"github":"duckduckgo"}	offline
elementaryos_stackexchange	elementary OS Stack Exchange	Question and answer site for for developers and users of elementary OS and applications	DDG::Longtail::elementary OS	live	live	longtail	elementary OS Stack Exchange	0	elementaryos.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	elementaryos_stackexchange	1	1	{"github":"duckduckgo"}	offline
ell_stackexchange	English Language Learners Stack Exchange	Question and answer site for speakers of other languages learning English	DDG::Longtail::English Language Learners	live	live	longtail	English Language Learners Stack Exchange	0	ell.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	ell_stackexchange	1	1	{"github":"duckduckgo"}	offline
emacs_stackexchange	Emacs Stack Exchange	Question and answer site for those using, extending or developing Emacs	DDG::Longtail::Emacs	live	live	longtail	Emacs Stack Exchange	0	emacs.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	emacs_stackexchange	1	1	{"github":"duckduckgo"}	offline
engineering_stackexchange	Engineering Stack Exchange	Question and answer site for professionals and students of engineering	DDG::Longtail::Engineering	live	live	longtail	Engineering Stack Exchange	0	engineering.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	engineering_stackexchange	1	1	{"github":"duckduckgo"}	offline
ethereum_stackexchange	Ethereum Stack Exchange	Question and answer site for users of Ethereum, the crypto value and blockchain-based consensus network	DDG::Longtail::Ethereum	live	live	longtail	Ethereum Stack Exchange	0	ethereum.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	ethereum_stackexchange	1	1	{"github":"duckduckgo"}	offline
expatriates_stackexchange	Expatriates Stack Exchange	Question and answer site for people living abroad on a long-term basis	DDG::Longtail::Expatriates	live	live	longtail	Expatriates Stack Exchange	0	expatriates.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	expatriates_stackexchange	1	1	{"github":"duckduckgo"}	offline
expressionengine_stackexchange	ExpressionEngine Stack Exchange	Question and answer site for administrators, end users, developers and designers for ExpressionEngine® CMS	DDG::Longtail::ExpressionEngine	live	live	longtail	ExpressionEngine Stack Exchange	0	expressionengine.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	expressionengine_stackexchange	1	1	{"github":"duckduckgo"}	offline
fitness_stackexchange	Fitness Stack Exchange	Question and answer site for physical fitness professionals, athletes, trainers, and those providing health-related needs	DDG::Longtail::Fitness	live	live	longtail	Fitness Stack Exchange	0	fitness.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	fitness_stackexchange	1	1	{"github":"duckduckgo"}	offline
freelancing_stackexchange	Freelancing Stack Exchange	Question and answer site for self-employed and freelance workers	DDG::Longtail::Freelancing	live	live	longtail	Freelancing Stack Exchange	0	freelancing.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	freelancing_stackexchange	1	1	{"github":"duckduckgo"}	offline
french_stackexchange	French Stack Exchange	Question and answer site for students, teachers, and linguists wanting to discuss the finer points of the French language	DDG::Longtail::French	live	live	longtail	French Stack Exchange	0	french.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	french_stackexchange	1	1	{"github":"duckduckgo"}	offline
gardening_stackexchange	Gardening & Landscaping Stack Exchange	Question and answer site for gardeners and landscapers	DDG::Longtail::Gardening	live	live	longtail	Gardening & Landscaping Stack Exchange	0	gardening.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	gardening_stackexchange	1	1	{"github":"duckduckgo"}	offline
genealogy_stackexchange	Genealogy & Family History Stack Exchange	Question and answer site for expert genealogists and people interested in genealogy or family history	DDG::Longtail::Genealogy	live	live	longtail	Genealogy & Family History Stack Exchange	0	genealogy.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	genealogy_stackexchange	1	1	{"github":"duckduckgo"}	offline
german_stackexchange	German Language Stack Exchange	Question and answer site for speakers of all levels who want to share and increase their knowledge of the German language	DDG::Longtail::GermanLanguage	live	live	longtail	German Language Stack Exchange	0	german.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	german_stackexchange	1	1	{"github":"duckduckgo"}	offline
graphicdesign_stackexchange	Graphic Design Stack Exchange	Question and answer site for Graphic Design professionals, students, and enthusiasts	DDG::Longtail::GraphicDesign	live	live	longtail	Graphic Design Stack Exchange	0	graphicdesign.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	graphicdesign_stackexchange	1	1	{"github":"duckduckgo"}	offline
ham_stackexchange	Amateur Radio Stack Exchange	Question and answer site for amateur radio enthusiasts	DDG::Longtail::AmateurRadio	live	live	longtail	Amateur Radio Stack Exchange	0	ham.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	ham_stackexchange	1	1	{"github":"duckduckgo"}	offline
hardwarerecs_stackexchange	Hardware Recommendations Stack Exchange	Question and answer site for people seeking specific hardware recommendations	DDG::Longtail::Hardware Recommendations	live	live	longtail	Hardware Recommendations Stack Exchange	0	hardwarerecs.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	hardwarerecs_stackexchange	1	1	{"github":"duckduckgo"}	offline
health_stackexchange	Health Stack Exchange	Question and answer site for medical specialists, students, dietitians, and anyone with health-related questions	DDG::Longtail::Health	live	live	longtail	Health Stack Exchange	0	health.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	health_stackexchange	1	1	{"github":"duckduckgo"}	offline
hermeneutics_stackexchange	Biblical Hermeneutics Stack Exchange	Question and answer site for professors, theologians, and those interested in exegetical analysis of biblical texts	DDG::Longtail::Biblical Hermeneutics	live	live	longtail	Biblical Hermeneutics Stack Exchange	0	hermeneutics.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	hermeneutics_stackexchange	1	1	{"github":"duckduckgo"}	offline
hinduism_stackexchange	Hinduism Stack Exchange	Question and answer site for followers of the Hindu religion and those interested in learning more about Hinduism	DDG::Longtail::Hinduism	live	live	longtail	Hinduism Stack Exchange	0	hinduism.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	hinduism_stackexchange	1	1	{"github":"duckduckgo"}	offline
history_stackexchange	History Stack Exchange	Question and answer site for historians and history buffs	DDG::Longtail::History	live	live	longtail	History Stack Exchange	0	history.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	history_stackexchange	1	1	{"github":"duckduckgo"}	offline
hsm_stackexchange	History of Science and Mathematics Stack Exchange	Question and answer site for people interested in the history and origins of science and mathematics	DDG::Longtail::HSM	live	live	longtail	History of Science and Mathematics Stack Exchange	0	hsm.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	hsm_stackexchange	1	1	{"github":"duckduckgo"}	offline
islam_stackexchange	Islam Stack Exchange	Question and answer site for Muslims, experts in Islam, and those interested in learning more about Islam	DDG::Longtail::Islam	live	live	longtail	Islam Stack Exchange	0	islam.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	islam_stackexchange	1	1	{"github":"duckduckgo"}	offline
italian_stackexchange	Italian Language Stack Exchange	Question and answer site for students, teachers, and linguists wanting to discuss the finer points of the Italian language	DDG::Longtail::ItalianLanguage	live	live	longtail	Italian Language Stack Exchange	0	italian.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	italian_stackexchange	1	1	{"github":"duckduckgo"}	offline
joomla_stackexchange	Joomla Stack Exchange	Question and answer site for Joomla! administrators, users, developers and designers	DDG::Longtail::Joomla	live	live	longtail	Joomla Stack Exchange	0	joomla.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	joomla_stackexchange	1	1	{"github":"duckduckgo"}	offline
law_stackexchange	Law Stack Exchange	Question and answer site for legal professionals, students, and others with experience or interest in law	DDG::Longtail::Law	live	live	longtail	Law Stack Exchange	0	law.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	law_stackexchange	1	1	{"github":"duckduckgo"}	offline
lifehacks_stackexchange	Lifehacks Stack Exchange	Question and answer site for people looking to bypass life's everyday problems with simple tricks	DDG::Longtail::Lifehacks	live	live	longtail	Lifehacks Stack Exchange	0	lifehacks.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	lifehacks_stackexchange	1	1	{"github":"duckduckgo"}	offline
linguistics_stackexchange	Linguistics Stack Exchange	Question and answer site for professional linguists and others with an interest in linguistic research and theory	DDG::Longtail::Linguistics	live	live	longtail	Linguistics Stack Exchange	0	linguistics.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	linguistics_stackexchange	1	1	{"github":"duckduckgo"}	offline
magento_stackexchange	Magento Stack Exchange	Question and answer site for users of the Magento e-Commerce platform	DDG::Longtail::Magento	live	live	longtail	Magento Stack Exchange	0	magento.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	magento_stackexchange	1	1	{"github":"duckduckgo"}	offline
martialarts_stackexchange	Martial Arts Stack Exchange	Question and answer site for students and teachers of all martial arts	DDG::Longtail::MartialArts	live	live	longtail	Martial Arts Stack Exchange	0	martialarts.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	martialarts_stackexchange	1	1	{"github":"duckduckgo"}	offline
matheducators_stackexchange	Math Educators Stack Exchange	Question and answer site for those involved in the field of teaching mathematics	DDG::Longtail::MathEducators	live	live	longtail	Math Educators Stack Exchange	0	matheducators.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	matheducators_stackexchange	1	1	{"github":"duckduckgo"}	offline
mechanics_stackexchange	Motor Vehical Maintenance & Repair Stack Exchange	Question and answer site for mechanics and DIY enthusiast owners of cars, trucks, and motorcycles	DDG::Longtail::Mechanics	live	live	longtail	Motor Vehical Maintenance & Repair Stack Exchange	0	mechanics.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	mechanics_stackexchange	1	1	{"github":"duckduckgo"}	offline
moderators_stackexchange	Community Building Stack Exchange	Question and answer site for community managers, administrators, and moderators	DDG::Longtail::CommunityBuilding	live	live	longtail	Community Building Stack Exchange	0	moderators.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	moderators_stackexchange	1	1	{"github":"duckduckgo"}	offline
movies_stackexchange	Movies & TV Stack Exchange	Question and answer site for movie and tv enthusiasts	DDG::Longtail::MoviesTV	live	live	longtail	Movies & TV Stack Exchange	0	movies.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	movies_stackexchange	1	1	{"github":"duckduckgo"}	offline
music_stackexchange	Music: Practice & Theory Stack Exchange	Question and answer site for musicians, students, and enthusiasts	DDG::Longtail::MusicPracticeTheory	live	live	longtail	Music: Practice & Theory Stack Exchange	0	music.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	music_stackexchange	1	1	{"github":"duckduckgo"}	offline
musicfans_stackexchange	Music Fans Stack Exchange	Question and answer site for music historians, critics, and fans	DDG::Longtail::MusicFans	live	live	longtail	Music Fans Stack Exchange	0	musicfans.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	musicfans_stackexchange	1	1	{"github":"duckduckgo"}	offline
mythology_stackexchange	Mythology Stack Exchange	Question and answer site for enthusiasts and scholars of mythology	DDG::Longtail::Mythology	live	live	longtail	Mythology Stack Exchange	0	mythology.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	mythology_stackexchange	1	1	{"github":"duckduckgo"}	offline
networkengineering_stackexchange	Network Engineering Stack Exchange	Question and answer site for network engineers	DDG::Longtail::NetworkEngineering	live	live	longtail	Network Engineering Stack Exchange	0	networkengineering.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	networkengineering_stackexchange	1	1	{"github":"duckduckgo"}	offline
opendata_stackexchange	Open Data Stack Exchange	Question and answer site for developers and researchers interested in open data	DDG::Longtail::OpenData	live	live	longtail	Open Data Stack Exchange	0	opendata.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	opendata_stackexchange	1	1	{"github":"duckduckgo"}	offline
opensource_stackexchange	Open Source Stack Exchange	Question and answer site for people organizing, marketing or licensing open source development projects	DDG::Longtail::OpenSource	live	live	longtail	Open Source Stack Exchange	0	opensource.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	opensource_stackexchange	1	1	{"github":"duckduckgo"}	offline
outdoors_stackexchange	The Great Outdoors Stack Exchange	Question and answer site for people who love outdoor activities, excursions, and outdoorsmanship	DDG::Longtail::TheGreatOutdoors	live	live	longtail	The Great Outdoors Stack Exchange	0	outdoors.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	outdoors_stackexchange	1	1	{"github":"duckduckgo"}	offline
parenting_stackexchange	Parenting Stack Exchange	Question and answer site for parents, grandparents, nannies and others with a parenting role	DDG::Longtail::Parenting	live	live	longtail	Parenting Stack Exchange	0	parenting.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	parenting_stackexchange	1	1	{"github":"duckduckgo"}	offline
askpatents_stackexchange	Ask Patents Stack Exchange	Question and answer site for people interested in improving and participating in the patent system	DDG::Longtail::AskPatents	live	live	longtail	Ask Patents Stack Exchange	0	askpatents.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	askpatents_stackexchange	1	1	{"github":"duckduckgo"}	offline
pets_stackexchange	Pets Stack Exchange	Question and answer site for pet owners, caretakers, breeders, veterinarians, and trainers	DDG::Longtail::Pets	live	live	longtail	Pets Stack Exchange	0	pets.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	pets_stackexchange	1	1	{"github":"duckduckgo"}	offline
philosophy_stackexchange	Philosophy Stack Exchange	Question and answer site for those interested in logical reasoning	DDG::Longtail::Philosophy	live	live	longtail	Philosophy Stack Exchange	0	philosophy.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	philosophy_stackexchange	1	1	{"github":"duckduckgo"}	offline
pm_stackexchange	Project Management Stack Exchange	Question and answer site for project managers	DDG::Longtail::ProjectManagement	live	live	longtail	Project Management Stack Exchange	0	pm.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	pm_stackexchange	1	1	{"github":"duckduckgo"}	offline
poker_stackexchange	Poker Stack Exchange	Question and answer site for serious players and enthusiasts of poker	DDG::Longtail::Poker	live	live	longtail	Poker Stack Exchange	0	poker.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	poker_stackexchange	1	1	{"github":"duckduckgo"}	offline
poltics_stackexchange	Poltics Stack Exchange	Question and answer site for people interested in governments, policies, and political processes	DDG::Longtail::Poltics	live	live	longtail	Poltics Stack Exchange	0	poltics.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	poltics_stackexchange	1	1	{"github":"duckduckgo"}	offline
portuguese_stackexchange	Portuguese Language Stack Exchange	Question and answer site for linguists, teachers and learners wanting to discuss the finer points of the Portuguese language	DDG::Longtail::PortugueseLanguage	live	live	longtail	Portuguese Language Stack Exchange	0	portuguese.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	portuguese_stackexchange	1	1	{"github":"duckduckgo"}	offline
productivity_stackexchange	Personal Productivity Stack Exchange	Question and answer site for people wanting to improve their personal productivity	DDG::Longtail::PersonalProductivity	live	live	longtail	Personal Productivity Stack Exchange	0	productivity.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	productivity_stackexchange	1	1	{"github":"duckduckgo"}	offline
puzzling_stackexchange	Puzzling Stack Exchange	Question and answer site for those who create, solve, and study puzzles	DDG::Longtail::Puzzling	live	live	longtail	Puzzling Stack Exchange	0	puzzling.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	puzzling_stackexchange	1	1	{"github":"duckduckgo"}	offline
quant_stackexchange	Quantitative Finance Stack Exchange	Question and answer site for finance professionals and academics	DDG::Longtail::QuantitativeFinance	live	live	longtail	Quantitative Finance Stack Exchange	0	quant.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	quant_stackexchange	1	1	{"github":"duckduckgo"}	offline
raspberrypi_stackexchange	Raspberry Pi Stack Exchange	Question and answer site for users and developers of hardware and software for Raspberry Pi	DDG::Longtail::RaspberryPi	live	live	longtail	Raspberry Pi Stack Exchange	0	raspberrypi.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	raspberrypi_stackexchange	1	1	{"github":"duckduckgo"}	offline
reverseengineering_stackexchange	Reverse Engineering Stack Exchange	Question and answer site for researchers and developers who explore the principles of a system through analysis of its structure, function, and operation	DDG::Longtail::ReverseEngineering	live	live	longtail	Reverse Engineering Stack Exchange	0	reverseengineering.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	reverseengineering_stackexchange	1	1	{"github":"duckduckgo"}	offline
robotics_stackexchange	Robotics Stack Exchange	Question and answer site for professional robotic engineers, hobbyists, researchers and students	DDG::Longtail::Robotics	live	live	longtail	Robotics Stack Exchange	0	robotics.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	robotics_stackexchange	1	1	{"github":"duckduckgo"}	offline
salesforce_stackexchange	Salesforce Stack Exchange	Question and answer site for Salesforce administrators, implementation experts, developers and anybody in-between	DDG::Longtail::Salesforce	live	live	longtail	Salesforce Stack Exchange	0	salesforce.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	salesforce_stackexchange	1	1	{"github":"duckduckgo"}	offline
scicomp_stackexchange	Computational Science Stack Exchange	Question and answer site for scientists using computers to solve scientific problems	DDG::Longtail::ComputationalScience	live	live	longtail	Computational Science Stack Exchange	0	scicomp.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	scicomp_stackexchange	1	1	{"github":"duckduckgo"}	offline
softwarerecs_stackexchange	Software Recommendations Stack Exchange	Question and answer site for people seeking specific software recommendations	DDG::Longtail::SoftwareRecommendations	live	live	longtail	Software Recommendations Stack Exchange	0	softwarerecs.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	softwarerecs_stackexchange	1	1	{"github":"duckduckgo"}	offline
sound_stackexchange	Sound Design Stack Exchange	Question and answer site for sound engineers, producers, editors, and enthusiasts	DDG::Longtail::SoundDesign	live	live	longtail	Sound Design Stack Exchange	0	sound.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	sound_stackexchange	1	1	{"github":"duckduckgo"}	offline
space_stackexchange	Space Exploration Stack Exchange	Question and answer site for spacecraft operators, scientists, engineers, and enthusiasts	DDG::Longtail::Space Exploration	live	live	longtail	Space Exploration Stack Exchange	0	space.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	space_stackexchange	1	1	{"github":"duckduckgo"}	offline
spanish_stackexchange	Spanish Language Stack Exchange	Question and answer site for students, teachers, and linguists wanting to discuss the finer points of the Spanish language	DDG::Longtail::SpanishLanguage	live	live	longtail	Spanish Language Stack Exchange	0	spanish.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	spanish_stackexchange	1	1	{"github":"duckduckgo"}	offline
sports_stackexchange	Sports Stack Exchange	Question and answer site for participants in team and individual sport activities	DDG::Longtail::Sports	live	live	longtail	Sports Stack Exchange	0	sports.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	sports_stackexchange	1	1	{"github":"duckduckgo"}	offline
sqa_stackexchange	Software Quality Assurance Stack Exchange	Question and answer site for software quality control experts, automation engineers, and software testers	DDG::Longtail::Software Quality Assurance	live	live	longtail	Software Quality Assurance Stack Exchange	0	sqa.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	sqa_stackexchange	1	1	{"github":"duckduckgo"}	offline
stackapps	Stack Apps	Question and answer site for apps, scripts, and development with the Stack Exchange API	DDG::Longtail::StackApps	live	live	longtail	Stack Apps	0	stackapps.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	stackapps	1	1	{"github":"duckduckgo"}	offline
startups_stackexchange	Startups Stack Exchange	Question and answer site for entrepreneurs faced with delivering a new product or service under conditions of significant uncertainty	DDG::Longtail::Startups	live	live	longtail	Startups Stack Exchange	0	startups.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	startups_stackexchange	1	1	{"github":"duckduckgo"}	offline
sustainability_stackexchange	Sustainable Living Stack Exchange	Question and answer site for folks dedicated to a lifestyle that can be maintained indefinitely without depleting available resources	DDG::Longtail::SustainableLiving	live	live	longtail	Sustainable Living Stack Exchange	0	sustainability.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	sustainability_stackexchange	1	1	{"github":"duckduckgo"}	offline
tor_stackexchange	Tor Stack Exchange	Question and answer site for researchers, developers, and users of Tor	DDG::Longtail::Tor	live	live	longtail	Tor Stack Exchange	0	tor.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	tor_stackexchange	1	1	{"github":"duckduckgo"}	offline
tridion_stackexchange	Tridion Stack Exchange	Question and answer site for Tridion developers and administrators	DDG::Longtail::Tridion	live	live	longtail	Tridion Stack Exchange	0	tridion.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	tridion_stackexchange	1	1	{"github":"duckduckgo"}	offline
vi_stackexchange	Vi & Vim Stack Exchange	Question and answer site for people using the vi and Vim families of text editors	DDG::Longtail::ViVim	live	live	longtail	Vi & Vim Stack Exchange	0	vi.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	vi_stackexchange	1	1	{"github":"duckduckgo"}	offline
windowsphone_stackexchange	Windows Phone Stack Exchange	Question and answer site for enthusiasts and power users of Windows Phone OS	DDG::Longtail::Windows Phone	live	live	longtail	Windows Phone Stack Exchange	0	windowsphone.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	windowsphone_stackexchange	1	1	{"github":"duckduckgo"}	offline
woodworking_stackexchange	Woodworking Stack Exchange	Question and answer site for professional and amateur woodworkers	DDG::Longtail::Woodworking	live	live	longtail	Woodworking Stack Exchange	0	woodworking.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	woodworking_stackexchange	1	1	{"github":"duckduckgo"}	offline
workplace_stackexchange	Workplace Stack Exchange	Question and answer site for members of the workforce navigating the professional setting	DDG::Longtail::Workplace	live	live	longtail	Workplace Stack Exchange	0	workplace.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	workplace_stackexchange	1	1	{"github":"duckduckgo"}	offline
worldbuilding_stackexchange	Worldbuilding Stack Exchange	Question and answer site for writers/artists using science, geography and culture to construct imaginary worlds and settings	DDG::Longtail::Worldbuilding	live	live	longtail	Worldbuilding Stack Exchange	0	worldbuilding.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	worldbuilding_stackexchange	1	1	{"github":"duckduckgo"}	offline
writers_stackexchange	Writers Stack Exchange	Question and answer site for authors, editors, reviewers, professional writers, and aspiring writers	DDG::Longtail::Writers	live	live	longtail	Writers Stack Exchange	0	writers.stackexchange.com	[{"url":"http://www.duckduckhack.com","name":"DDG Team","type":"ddg"}]	writers_stackexchange	1	1	{"github":"duckduckgo"}	offline
\.
