# PODNAME: DDGC::Manual::TODO
# ABSTRACT: TODO Tasks

=encoding utf-8

=head1 Design

Making the token domain language overview on translate/index hidden, load it
via ajax on request. Clicking on token domain leads then to language overview
instead of direct translation.

There is no visual difference between language the user speaks and the ones the
user doesnt speak. In favour of "hey lets look at other languages" i dont
wanted it limited to only the languages the user speaks. Also prevent display
of english language name on english languages ;).

=head1 Design Errors

Linebreak on the userinfo box topleft.

Tokenpage has space between the language dropdown/breadcrumb and the actual
token list.
